apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
profiles:
  - name: local
    activation:
      - kubeContext: "default"
    build:
      local:
        push: false
  - name: gcr
    build:
      googleCloudBuild:
        projectId: ${GCP_PROJECT_ID}

